- name: Install Catalogue
  hosts: catalogue
  become: yes 
  tasks:
  - name: set up NPM sources
    tags:
    - installation
    ansible.builtin.shell: "https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install nodejs
    tags:
    - installation
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: checking exists roboshop user
    tags:
    - installation
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  #when: out.rc != 0 
  - name: create user roboshop
    tags:
    - installation
    when: out.rc != 0
    ansible.builtin.user: 
      name: roboshop

  - name: checl/ app directory exists or not
    tags:
    - installation 
    ansible.builtin.stat:
      path: /app
    register: directory          

  - name: print the directory stats
    tags:
    - installation
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - name: create directory  /app
    tags:
    - installation
    when: directory.stat.exists == False
    ansible.builtin.file:
      path: /app
      state: directory  

  - name: download catalogue artifacts
    tags:
    - deployment
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue artifact
    tags:
    - deployment
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app 
      remote_src: yes

  - name: install dependencies
    tags:
    - deployment
    ansible.builtin.command: npm install 
    args:
      chdir:  /app 

  - name: copy catalogue.service
    tags:
    - installation
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: demon reload
    tags:
    - installation
    ansible.builtin.systemd:
      daemon_reload: true  

  - name: copy mango.repo to yum.repos.d
    tags:
    - installation
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo 

  - name: Install Mongodb
    tags:
    - installation
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: load catlogue data into mongodb
    tags:
    - installation
    ansible.builtin.command: mongo --host 172.31.32.167 < /app/schema/catalogue.js

  - name: restart and enable catalogue
    tags:
    - deployment
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes   