- name: understand facts
  hosts: centos:ubuntu #all 
  become: yes 
  tasks:
  - name: print the all fact
    ansible.builtin.debug:
      msg: "all facts: {{ansible_facts}}"

  - name: add user ubuntu
    ansible.builtin.command: adduser chandu
    when: ansible_facts['distribution'] == "Ubuntu"

  
  - name: add user centos
    ansible.builtin.command: useradd chandu
    when: ansible_facts['distribution'] == "CentOs"   
      