- name: demo on filters
  hosts: localhost
  vars:
    NAME: chandu
    website: https://www.joindevops.com/batch-74s
    greetings: hi ram, how are you 
  tasks:
  - name: convert into upper case
    debug:
      msg: "hello {{ NAME | upper }}"  

  - name: convert into lower case
    debug:
      msg: "hello {{ NAME | lower }}"

  - name: printing undefined variables
    debug:
      msg: "hell {{COURSE | default ('Devops')}}"          

  - name: extract host name
    debug:
      msg: "hell {{website | urlsplit ('hostname')}}"

  - name: split values
    debug:
      msg: "hell {{greetings | split (',')}}"              