- name: demo on filters
  hosts: localhost
  vars:
    NAME: chandu
  tasks:
  - name: convert into upper case
    debug:
      msg: "hello {{ NAME | upper }}"  

  - name: convert into lower case
    debug:
      msg: "hello {{ NAME | lower }}"

  - name: printing undefined variables
    debug:
      msg: "hell {{COURSE | default ('Devops')}}"          