- name: demo on filters
  hosts: localhost
  vars:
    NAME: chandu
    website: devara.chandrasekhar1@tcs.com
  tasks:
  - name: convert into upper case
    debug:
      msg: "hello {{ NAME | upper }}"  

  - name: convert into lower case
    debug:
      msg: "hello {{ NAME | lower }}"

  - name: printing undefined variables
    debug:
      msg: "hell {{COURSE | default ('Devops')}}"          

  - name: extract host name
    debug:
      msg: "hell {{website | urlsplit ('hostname')}}"     